package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.62

import (
	"context"
	"gqlgen-test/api/ephemeral/graph"
)

// Parrot is the resolver for the parrot field.
func (r *queryResolver) Parrot(ctx context.Context, input any) (any, error) {
	return input, nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
